# ======================================================
# GitHub Actions Workflow for Android CI
# ======================================================
# This workflow builds the app, runs unit tests,
# and runs instrumented UI tests on an Android Emulator.
# ------------------------------------------------------

name: Android CI

# ------------------------------------------------------
# Trigger workflow on pushes & pull requests to main
# ------------------------------------------------------
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # ======================================================
  # JOB 1: Unit Tests
  # ------------------------------------------------------
  # Runs fast JVM tests (no emulator needed).
  # Verifies business logic, ViewModels, services, etc.
  # ======================================================
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest  # GitHub-hosted Ubuntu runner

    steps:
      # Step 1: Pull code from GitHub repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java Development Kit (JDK 17 required by Android Gradle plugin)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin   # Recommended OpenJDK
          java-version: 17

      # Step 3: Cache Gradle dependencies to speed up builds
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          # Cache Gradle's local files
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          # Unique key per OS + Gradle files hash
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Make Gradle wrapper executable (fixes "permission denied" errors)
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      # Step 5: Compile + build APK in debug mode
      - name: Build project
        run: ./gradlew assembleDebug

      # Step 6: Run JVM unit tests (fast tests, no emulator needed)
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      # Optional: Upload APK as artifact so testers can download it
      #- name: Upload APK artifact
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: debug-apk
      #    path: app/build/outputs/apk/debug/app-debug.apk
